# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/8aeb4d7b-3b2b-418e-9116-14f9cf2afa52";
    fsType = "ext4";
  };

  boot.initrd.luks.devices."luks-817a9674-fc77-460b-ab46-f8092c15a56f".device = "/dev/disk/by-uuid/817a9674-fc77-460b-ab46-f8092c15a56f";

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2CC6-A789";
    fsType = "vfat";
  };

  swapDevices = [
    {device = "/dev/disk/by-uuid/f2071214-479d-42d8-a0eb-69ca7c807d92";}
  ];

  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
